config/routes.rb
VoltaicLife::Application.routes.draw do
  get "search/index"
  get "welcome/index"
  devise_for :users
  resources :statuses
  
  root to: 'welcome#index'

  

end

app/models/search.rb
class Search < ActiveRecord::Base
  attr_accessible :artist, :venue, :zipcode
  
  CHOICES = ['artist', 'venue', 'zipcode']
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :content, :user_id
  belongs_to :user
  
  validates :content, presence: true,
                      length: { minimum: 2 }

  validates :user_id, presence: true
  
  has_attached_file :avatar
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :avatar, :first_name, :last_name, :profile_name,  :email, :password, :password_confirmation, :remember_me, :full_name
  
    validates :first_name, presence: true

  validates :last_name, presence: true

  validates :profile_name, presence: true,
                           uniqueness: true,
                           format: {
                             with: /[a-zA-Z0-9_-]/,
                             message: 'Must be formatted correctly.'
                           }
  
  has_attached_file :avatar, :styles => {:medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

 
  has_many :statuses
 
  def full_name
    [first_name, last_name].join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :first_name
   devise_parameter_sanitizer.for(:sign_up) << :last_name
   devise_parameter_sanitizer.for(:sign_up) << :profile_name
  end

  def create
    @user = User.create( params[:user] )
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by_profile_name(params[:id])
    if @user
      @statuses = @user.statuses.all
      render action: :show
    else
      render file: 'public/404', status: 404, formats: [:html]
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :content)
    end
end

app/controllers/welcome_controller.rb
require 'net/http'

class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(type)
    case type
    when :alert
      "alert-error"
    when :notice
      "alert-success"
    else
      ""
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VoltaicLife</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="wrap">
			<div class="navbar navbar-fixed-top">
				<div class="navbar-inner">
					<div class="conatiner">
									<%= link_to "VoltaicLife", root_path, {class: "brand"} %>
									<ul class="nav pull-right">
										<% if user_signed_in?%>					
											<li class="top form-search"><%= form_tag("/search", method: "get") do %>
												<%= select_tag "search by", options_for_select(%w{ band venue zipcode }) %>
	 											 <%= text_field_tag(:q) %>
	  												<%= submit_tag("Search") %>
												<% end %></li>
											<li><%= link_to current_user.full_name, edit_user_registration_path %></li>
											<li><%= link_to "Log out",  destroy_user_session_path, method: :delete %></li>
										<% else %>
											<li><%= link_to "Login",  new_user_session_path %></li>
										<% end %>
									</ul>
					</div>
				</div>
			</div>

	<div class="container mainBody">
		<% flash.each do |type, message| %>
			<div class="alert <%= flash_class type %>">
				<button class="close" data-dismiss="alert">×</button>
				<%= message %>
			</div>
		<% end %>
		
		<%= yield %>
	</div>
	</div>
     <div id="footer">
      <div class="container">
        <p class="muted credit">&copy; 2013 VoltaicLife, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a>.</p>
      </div>
    </div>

</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
  <h1><%= @user.full_name %></h1>
</div>

<% if @statuses %>
  <% @statuses.each do |status| %>
    <div class="well">
      <%= status.content %>
      <hr />
      <%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
    </div>
  <% end %>
<% end %>

app/views/search/index.html.erb
<h1>Search Results.../h1>
<hr />
    <% @search.each do |status| %>
    <div class="results">
    	

	 </div>
	 
    <% end %>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<%= f.input :content%>
		
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
	<h1>Feed</h1>
</div>

    <% @statuses.each do |status| %>
    <div class="status">
    	<strong><%= status.user.full_name %></strong>
    	<p><%= status.content %></p>

		<div class="meta">
			<%= link_to time_ago_in_words(status.created_at) + " ago", status %>
			<span class="admin">
			<%= link_to 'Edit', edit_status_path(status) %> |
			<%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %>
			</span>
		</div>
	 </div>
	 
    <% end %>


<br>

<%= link_to 'New Status', new_status_path, class: "btn" %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @user.avatar.url(:thumb) %>
  <strong><%= @status.user.full_name %></strong>
</p>

<p>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>

app/views/welcome/_form.html.erb
<div class="span7 offset2">
	<%= form_tag("/search", method: "get", html: {class: "form-inline"}) do %>
	<%= select_tag "search by", options_for_select(%w{ Artist Venue Zipcode }) %>
	  <%= text_field_tag(:q) %>
	  <%= submit_tag("Search") %>
	<% end %>
</div>

app/views/welcome/index.html.erb
<div  id="ctaSlide"  class="carousel slide">
  <div class="carousel-inner">
    <div class="item active">
    	<%= image_tag ("1.jpg")%>
    </div>
    <div class="item">
      <%= image_tag ("2.jpg")%>
    </div>
    <div class="item">
      <%= image_tag ("3.jpg")%>
    </div>
    <div class="item">
     <%= image_tag ("4.jpg")%>
    </div>
    <div class="item">
     <%= image_tag ("5.jpg")%>
    </div>
    <div class="item">
      <%= image_tag ("6.jpg")%>
    </div>
    <div class="item">
     <%= image_tag ("7.jpg")%>
    </div>
     <div class="item">
     <%= image_tag ("8.jpg")%>
    </div>
     <div class="item">
     <%= image_tag ("9.jpg")%>
    </div>
     <div class="item">
     <%= image_tag ("10.JPG")%>
    </div>
     <div class="item">
     <%= image_tag ("11.jpg")%>
    </div>
  </div>
      <a class="left carousel-control" href="#ctaSlide" data-slide="prev">&lsaquo;</a>
      <a class="right carousel-control" href="#ctaSlide" data-slide="next">&rsaquo;</a>
</div>

      <hr class="featurette-divider">

      <div class="featurette">
        <img class="featurette-image pull-right" >
        <h2 class="featurette-heading">Search to see who's playing near you. <span class="muted">It may blow your mind.</span></h2>
        <p class="lead text-center">Search by Artist name,Venue and even your Zipcode.</p>
      </div>
      
 <%= render 'form' %>